export default {
  module_list: [
    'lan_config', 'modify_password', 'dhcp_server', 'software_upgrade', 'restore_factory', 'backup_and_restore', 'system_log', 'reboot', 'wan_config', 'mac_config', 'ept_manage', 'wlan_2g', 'wlan_5g', 'cloud', 'plugin_manage',
  ],
  app_version: '1.8.4',
  wireless2g_channel: ['auto', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13'],
  wireless2g_mode: ['11b', '11g', '11bg%20mixed', '11n', '11bgn%20mixed'],
  wireless2g_bandwidth: ['auto', '20MHz'],
  wan_rate: ['auto', '10H', '10F'],
  pppoe_dial_mode: ['auto', 'normal', 'special1', 'special2', 'special3', 'special4', 'special5', 'special6', 'special7'],
  pppoe_conn_mode: ['manual', 'auto', 'demand'],
  dhcpserver_mode: ['on', 'off', 'auto'],
  lan_mode: ['manual', 'auto'],
  dial_mode: ['dhcp', 'staticip', 'pppoe'],
  host_num_2g: 32,
  host_num_5g: 32,
  wireless5g_channel: ['auto', '36', '40', '44', '48', '149', '153', '157', '161', '165'],
  wireless5g_mode: ['11a/n%20mixed', '11a/n/ac%20mixed'],
  wireless5g_bandwidth: ['auto', '20MHz', '40MHz', '80MHz'],
  wireless_band: ['wireless2g', 'wireless5g'],
  wireless5g_vhtmubfer: 1,
  host_time_mng_type: 1,
  host_domain_mng: 1,
  eth_bandwidth: 1000,
  wlan_bs: 1,
  power_list: ['high', 'middle', 'low'],
  ipv6: 1,
  wifison: '1',
  wifison_mesh: '1',
  wifison_role: 'CAP',
  wan_port_detect: '1',
  switch_port_num: '3',
  power_position: 'right',
  hostname_max_len: 63,
};
